name: Verify Output

on:
  push
    
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
  
  job3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: mkdir -p dist
    - run: echo hello > dist/world.txt
    - name: Bash Script
      shell: 'bash'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chmod +x ./scripts/extract.sh
        sh ./scripts/extract.sh > dist/world.txt
    - uses: actions/upload-artifact@master
      with:
        name: hello-world-artifact
        path: dist/world.txt

  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
    - run: mkdir -p dist
    - uses: actions/download-artifact@master
      with:
        name: hello-world-artifact
        path: dist/world.txt
    - run: |
        cat /home/runner/work/sync-repos/sync-repos/dist/world.txt/world.txt
