name: Sync Action

on:
  push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call a Bash Script
        run: |
          chmod +x ./ftos-forks/sync-repos/scripts/extract.sh
          sh ./ftos-forks/sync-repos/scripts/extract.sh 
          
