name: Sync Action

on:
  push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: ftos-forks/checkout@v2
        
      - name: Bash Script
        shell: 'bash'
        run: |
          chmod +x ./ftos-forks/sync-repos/scripts/extract.sh
          sh ./ftos-forks/sync-repos/scripts/extract.sh 
          
