name: Sync Action

on:
  push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: ftos-forks/checkout@v2
      
      - name: List 
        shell: 'bash'
        run: ls
        
      - name: Bash Script
        shell: 'bash'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./scripts/extract.sh
          sh ./scripts/extract.sh 
          
