name: Sample Conditional Matrix Build

on: push

jobs:
    setup-build:
        runs-on: ubuntu-20.04
        outputs:
          matrix: ${{ steps.setup-matrix.outputs.matrix }}
        steps:
          - name: Checkout code
            uses: ftos-forks/checkout@v2

          - name: Get strategy configuration
            id: setup-matrix
            uses: ftos-forks/conditional-build-matrix@0.1.0
            with:
              inputFile: '.github/source-dest.json' 
              filter: '[?Source]'

          - name: Print Matrix 
            run: echo "matrix content ${{ steps.setup-matrix.outputs.matrix }} "
          
                
    json-matrix:
        runs-on: ubuntu-20.04
        needs: [setup-build]
        continue-on-error: false
        strategy:
          fail-fast: true
          max-parallel: 1
          matrix: ${{fromJson(needs.setup-build.outputs.matrix)}}
        steps:
            - name: Print
              run: |
                echo ${{ matrix.Source }}
                echo ${{ matrix.Destination }}
